.gitignore, apps/build/ci-static-apps.sh, apps/build/ci-test-apps.sh, engine/build/ci-static-engine.sh, engine/build/ci-test-engine.sh, plugins/build/ci-static-plugins.sh, plugins/build/ci-test-plugins.sh
Added missing build/ folders removed by .gitignore in initial upload
=> fix(engine): added missing build folders

apps/examples/simple-example/api/create-openapi-file.sh, apps/examples/simple-example/api/openapi.json, apps/examples/simple-example/src/simple_example/collector/collect_spawn.py, apps/examples/simple-example/src/simple_example/collector/query_concurrently.py, apps/examples/simple-example/src/simple_example/list_somethings.py, apps/examples/simple-example/src/simple_example/query_something.py, apps/examples/simple-example/src/simple_example/query_something_extended.py, apps/examples/simple-example/src/simple_example/save_something.py, apps/examples/simple-example/src/simple_example/shuffle/parallelize_event.py, apps/examples/simple-example/src/simple_example/shuffle/spawn_event.py, apps/examples/simple-example/src/simple_example/streams/something_event.py, plugins/auth/basic-auth/src/hopeit/basic_auth/decode.py, plugins/auth/basic-auth/src/hopeit/basic_auth/login.py, plugins/auth/basic-auth/src/hopeit/basic_auth/logout.py, plugins/auth/basic-auth/src/hopeit/basic_auth/refresh.py
Fixed titles in /api/docs for simple-example.
=> fix(apps): smaller titles for /api/docs

.github/workflows/hopeit-engine-qa.yml, README.md
=> feature(engine): CI action for QA

docs/Makefile, docs/source/apidocs/hopeit.app.rst, docs/source/apidocs/hopeit.cli.rst, docs/source/apidocs/hopeit.dataobjects.rst, docs/source/apidocs/hopeit.server.rst, docs/source/apidocs/hopeit.testing.rst, docs/source/apidocs/hopeit.toolkit.rst, docs/source/apidocs/hopeit.toolkit.storage.rst, docs/source/apidocs/index.rst, docs/source/benchmark/index.rst, engine/src/hopeit/app/__init__.py, engine/src/hopeit/app/config.py, engine/src/hopeit/app/context.py, engine/src/hopeit/cli/__init__.py, engine/src/hopeit/dataobjects/__init__.py, engine/src/hopeit/server/__init__.py, engine/src/hopeit/server/steps.py, engine/src/hopeit/server/streams.py, engine/src/hopeit/testing/__init__.py, engine/src/hopeit/toolkit/__init__.py, engine/src/hopeit/toolkit/storage/__init__.py
Added modules docstring with an overview of submodules.
Fixed some typos.
=> fix(docs): added modules overview

Makefile, apps/build/ci-static-apps.sh, engine/build/ci-static-engine.sh, engine/requirements-dev.txt, engine/requirements.txt, engine/setup.py, engine/src/hopeit/app/api.py, engine/src/hopeit/server/web.py, engine/src/hopeit/toolkit/auth.py, engine/src/hopeit/toolkit/storage/fs.py, engine/test/integration/toolkit/test_it_auth.py, plugins/auth/basic-auth/setup.py, plugins/build/ci-static-plugins.sh
=> fix(engine): updated package versions

engine/setup.py, engine/src/hopeit/toolkit/storage/fs.py, engine/test/unit/toolkit/storage/test_fs.py
=> fix(toolkit): fix storage bad strip json extension

.github/workflows/hopeit-engine-pypi-publishing.yml, Makefile, docs/source/quickstart/install.rst, engine/README.md, engine/setup.py
**IMPLEMENTATION:**
- - [x] create workflow 
- - [x] execution criteria: on releases published
=> feature(engine): CI Action for package publishing on PyPI

README.md, docs/source/apidocs/hopeit.app.rst, docs/source/apidocs/hopeit.cli.rst, docs/source/apidocs/hopeit.dataobjects.rst, docs/source/apidocs/hopeit.rst, docs/source/apidocs/hopeit.server.rst, docs/source/apidocs/hopeit.testing.rst, docs/source/apidocs/hopeit.toolkit.rst, docs/source/apidocs/hopeit.toolkit.storage.rst, docs/source/apidocs/index.rst, docs/source/conf.py, docs/source/deprecations.rst, docs/source/release-notes.rst, engine/README.md, engine/src/hopeit/server/version.py
Preparing for release 0.2.0rc1
=> Prepare release 0.2.0rc1

apps/examples/simple-example/src/simple_example/upload_something.py, engine/src/hopeit/app/context.py, engine/src/hopeit/server/engine.py, engine/src/hopeit/server/events.py, engine/src/hopeit/server/version.py, engine/src/hopeit/server/web.py, engine/src/hopeit/testing/apps.py, engine/test/mock_app/mock_multipart_event.py, engine/test/mock_app/mock_post_preprocess.py
=> fix(engine): add query_args to preprocess 

docs/source/release-notes.rst, engine/src/hopeit/dataobjects/jsonify.py, engine/src/hopeit/server/version.py, engine/src/hopeit/server/web.py
**FIX:**
Small fix on web module, remove unnecessary decode on reading payload.
=> fix(web): remove unnecessary decode when parsing payload 

engine/test/unit/streams/test_redis_streams.py
Added missing test file from previous PR.
No release / version update needed.
=> fix(engine): added missing test streams file.

.github/workflows/hopeit-engine-qa.yml
=> fix(ci): Enable qa on dev branches

plugins/ops/apps-visualizer/src/hopeit/apps_visualizer/events_graph_template.html
=> fix(plugins) app visualizer layout

plugins/ops/apps-visualizer/src/hopeit/apps_visualizer/events_graph.py, plugins/ops/apps-visualizer/src/hopeit/apps_visualizer/graphs.py, plugins/ops/apps-visualizer/test/integration/test_events_graph.py
fixed stream names when expand_queues=true
=> fix(plugins) apps_visualizer, fixed stream names when expand_queues=true

apps/examples/simple-example/api/openapi.json, plugins/ops/apps-visualizer/src/hopeit/apps_visualizer/events_graph.py, plugins/ops/apps-visualizer/src/hopeit/apps_visualizer/events_graph_template.html, plugins/ops/apps-visualizer/src/hopeit/apps_visualizer/graphs.py, plugins/ops/apps-visualizer/src/hopeit/apps_visualizer/visualization.py, plugins/ops/apps-visualizer/test/integration/events_graph_data.json, plugins/ops/apps-visualizer/test/integration/test_events_graph.py
Improving layout of Events Graph
=> plugin(app-visualizer): Bootstrap layout

docs/source/release-notes.rst, engine/src/hopeit/server/version.py, plugins/ops/apps-visualizer/MANIFEST.in, plugins/ops/apps-visualizer/setup.py
Fixes #81 
- Added html template to package_data in wheel
- Removed introduced MANIFEST.in approach in 0.4.1
=> fix(apps-visualizer): Added html template to package_data in wheel

README.md
Updated roadmap in README before release.
=> fix(docs) Updated readme roadmap

apps/examples/client-example/api/openapi.json, apps/examples/simple-example/api/openapi.json, docs/source/release-notes.rst, engine/src/hopeit/server/version.py, plugins/ops/apps-visualizer/api/openapi.json, plugins/ops/apps-visualizer/setup.py
Added missing packages in setup.py in apps_visualizer plugin.
=> fix(plugins): fixed apps-visualizer missing files in pypi dist

apps/examples/simple-example/src/simple_example/query_something_extended.py, docs/source/release-notes.rst, engine/src/hopeit/server/logger.py, engine/src/hopeit/server/version.py, engine/test/integration/test_it_logger.py
fix https://github.com/hopeit-git/hopeit.engine/issues/114
=> fix(engine): app_extra_logger debug level

.vscode/launch.json, apps/benchmark/simple-benchmark/api/openapi.json, apps/benchmark/simple-benchmark/test/benchmark-docker.sh, apps/benchmark/simple-benchmark/test/warm-up-fs.sh, apps/examples/client-example/api/openapi.json, apps/examples/simple-example/api/openapi.json, apps/examples/simple-example/config/app-config.json, apps/examples/simple-example/test/integration/test_it_process_events.py, docs/source/benchmark/dedicated.rst, docs/source/release-notes.rst, engine/config/schemas/app-config-schema-draftv6.json, engine/config/schemas/server-config-schema-draftv6.json, engine/src/hopeit/app/config.py, engine/src/hopeit/cli/server.py, engine/src/hopeit/server/config.py, engine/src/hopeit/server/engine.py, engine/src/hopeit/server/version.py, engine/src/hopeit/server/web.py, engine/test/integration/server/test_it_web.py, engine/test/mock_app/__init__.py, engine/test/mock_engine/__init__.py, engine/test/unit/server/test_engine.py, engine/test/unit/server/test_server.py, engine/test/unit/server/test_web.py, plugins/clients/apps-client/test/unit/__init__.py, plugins/ops/apps-visualizer/api/openapi.json, plugins/ops/apps-visualizer/src/hopeit/apps_visualizer/site/main.py, plugins/ops/config-manager/test/integration/runtime_simple_example.json, pylintrc
=> feature(engine): Specify groups of events to run at startup

apps/build/ci-static-apps.sh, apps/examples/client-example/api/openapi.json, apps/examples/simple-example/api/openapi.json, docs/source/release-notes.rst, engine/build/ci-static-engine.sh, engine/config/schemas/app-config-schema-draftv6.json, engine/config/schemas/server-config-schema-draftv6.json, engine/requirements-dev.txt, engine/requirements.lock, engine/requirements.txt, engine/src/hopeit/app/context.py, engine/src/hopeit/server/version.py, engine/src/hopeit/testing/hooks.py, plugins/build/ci-static-plugins.sh, plugins/ops/apps-visualizer/api/openapi.json, plugins/storage/redis/setup.py, plugins/storage/redis/src/hopeit/redis_storage/__init__.py, plugins/storage/redis/test/unit/test_redis_storage.py, plugins/streams/redis/setup.py, plugins/streams/redis/src/hopeit/redis_streams/__init__.py, plugins/streams/redis/test/unit/test_redis_streams.py
=> update(redis): switch from aioredis to redis library

.github/workflows/hopeit-engine-qa.yml
=> Enable CI for dev branch

apps/examples/client-example/api/openapi.json, apps/examples/simple-example/api/openapi.json, apps/examples/simple-example/src/simple_example/service/something_generator.py, docs/source/release-notes.rst, engine/config/schemas/app-config-schema-draftv6.json, engine/config/schemas/server-config-schema-draftv6.json, engine/src/hopeit/app/events.py, engine/src/hopeit/cli/openapi.py, engine/src/hopeit/cli/server.py, engine/src/hopeit/server/engine.py, engine/src/hopeit/server/version.py, engine/src/hopeit/server/web.py, engine/src/hopeit/testing/apps.py, engine/test/mock_app/__init__.py, engine/test/mock_app/mock_service_event_unhappy.py, engine/test/unit/server/test_engine.py, engine/test/unit/server/test_web.py, engine/test/unit/testing/test_apps.py, plugins/ops/apps-visualizer/api/openapi.json
=> feature(engine): add `service_running` to help gracefully shutdown of service events

docs/source/tutorials/01-first-app.rst
Fix reponse showed to match dataclass field names.
=> chore: fix tutorial 01-first-app.rst

apps/examples/client-example/api/openapi.json, apps/examples/client-example/config/app-config.json, apps/examples/client-example/src/client_example/call_unsecured.py, apps/examples/client-example/src/client_example/count_and_save.py, apps/examples/client-example/test/integration/test_it.py, apps/examples/simple-example/api/openapi.json, apps/examples/simple-example/config/app-config.json, apps/examples/simple-example/src/simple_example/list_somethings_unsecured.py, docs/source/release-notes.rst, engine/src/hopeit/server/version.py, plugins/clients/apps-client/src/hopeit/apps_client/__init__.py, plugins/clients/apps-client/test/unit/__init__.py, plugins/clients/apps-client/test/unit/conftest.py, plugins/clients/apps-client/test/unit/test_apps_client.py, plugins/ops/apps-visualizer/api/openapi.json, plugins/ops/apps-visualizer/test/integration/events_graph_data_standard.json, plugins/ops/config-manager/test/integration/runtime_simple_example.json, plugins/ops/config-manager/test/integration/test_runtime_apps_config.py, plugins/storage/redis/src/hopeit/redis_storage/__init__.py, plugins/storage/redis/test/unit/test_redis_storage.py
=> fix(apps-client): support UNSECURED AuthStrategy

apps/examples/client-example/api/openapi.json, apps/examples/dataframes-example/api/openapi.json, apps/examples/simple-example/api/openapi.json, engine/src/hopeit/server/version.py, plugins/data/dataframes/setup.py, plugins/ops/apps-visualizer/api/openapi.json
Fixed missing packages in setup file.
=> plugin(dataframes): fixed package imports

docs/source/release-notes.rst
=> chore(release-notes) added missing 0.24.1 entry in release notes

apps/examples/client-example/api/openapi.json, apps/examples/dataframes-example/api/openapi.json, apps/examples/simple-example/api/openapi.json, docs/source/release-notes.rst, engine/src/hopeit/server/version.py, engine/src/hopeit/testing/hooks.py, engine/test/unit/app/test_context.py, plugins/data/dataframes/src/hopeit/dataframes/dataframe.py, plugins/ops/apps-visualizer/api/openapi.json
- fix: construction from series to allow same way of usage as pd.DataFrame
- fix: remove index name when creating from indexed dataframe or series
=> plugin(dataframes):  fix construction from series

engine/test/unit/dataobjects/__init__.py, engine/test/unit/dataobjects/test_payload.py
Enabled tests disables in  beta release.
=> chore(engine): enabled tests for Payload parsing with missing fields

.github/workflows/hopeit-engine-pypi-publishing.yml, .github/workflows/hopeit-engine-test-pypi-publishing.yml, apps/examples/client-example/api/openapi.json, apps/examples/dataframes-example/api/openapi.json, apps/examples/simple-example/api/openapi.json, engine/src/hopeit/server/version.py, plugins/ops/apps-visualizer/api/openapi.json
Release 0.25.0b8 failed to publish.
Fixing deps install during publishing and bumping to 0.25.0b9
=> chore(ci): fix publishing
