hopeit-git/hopeit.engine

- .github/workflows/hopeit-engine-qa.yml
- engine/src/hopeit/server/engine.py
Problem description:
When no events of types STREAM are present in the app,
but still some events have write_stream specified in config,
StreamManager is not instantiated in engine:
Solution:
StreamManager must be created when event type is STREAM or write_stream is present in app configuration.
> fix(engine): create StreamManager when write_stream is present in config

- engine/src/hopeit/server/web.py
- engine/test/integration/server/test_it_web.py
- engine/test/mock_app/__init__.py
- engine/test/mock_app/mock_post_nopayload.py
Problem description:
When created a post event with payload:None type and no payload specified in API,
call to endpoint was failing trying to convert empty payload from Json.
Solution:
Now empty payloads are mapped to None object and step with payload:None is invoked.
> fix(engine): support POST with empty payload

- apps/examples/simple-example/api/openapi.json
- docs/source/deprecations.rst
- docs/source/index.rst
- engine/setup.py
- engine/src/hopeit/app/api.py
- engine/test/mock_app/__init__.py
- engine/test/mock_app/mock_app_api_get.py
- engine/test/mock_app/mock_app_api_get_list.py
- engine/test/mock_app/mock_app_api_post.py
- engine/test/mock_app/mock_app_api_title.py
- engine/test/unit/app/test_app_api.py
**PROBLEM:**
* In OpenAPI specs generation `summary` property is missing and there is no api to add it.
* `event_api` method use `title` parameter to set description property to the OpenAPI generated spec, this is confusing.  
**PROPOSAL:**
* Add to `event_api` method ``summary`` instead of ``title``, and `description` parameters and warn of deprecation in the usage of ``title`` starting on 0.1.4 hopeit.engine version, and removal on hopeit.engine 0.2.0
* if event_api don't provides method or description or any, try from module docstring.
**IMPLEMENTATION:**
Note that always `event_api` have precedence over docstring.
* for a given module with `summary` and `description` defined in `event_api` : 
```
"""
get-something
This method return something Object.
This is a second description line …
```
> fix(openapi): missing summary

- .github/workflows/hopeit-engine-pypi-publishing.yml
- README.md
> fix(engine): CI Action for package publishing on PyPI

- engine/requirements.lock
- engine/requirements.txt
- engine/src/hopeit/server/api.py
- engine/src/hopeit/server/version.py
Custom validator implemented for Multipart uploads on top of aiohttop_swagger3, threw unhandled TypeError on the presence of Nullable or Optional missing fields.
This PR solves the issue by:
After merge will release 0.2.0rc2
> fix(engine): swagger validator unhandled error with optional/nullable fields

- docs/source/apidocs/hopeit.rst
- docs/source/apidocs/hopeit.server.rst
- docs/source/apidocs/hopeit.streams.rst
- docs/source/release-notes.rst
- engine/setup.py
- engine/src/hopeit/server/__init__.py
- engine/src/hopeit/server/engine.py
- engine/src/hopeit/server/version.py
- engine/src/hopeit/streams/__init__.py
- engine/src/hopeit/streams/redis.py
- engine/test/integration/server/test_it_web.py
- engine/test/mock_engine/__init__.py
- engine/test/unit/server/test_engine.py
- engine/test/unit/server/test_streams.py
**INTERNAL CHANGE:**
Split StreamManager class to support specific implemenations. 
Move Redis Streams specifics to RedisStreamManager class.
This allows future creationg of different StreamManager implementions (i.e. for Kafka or embedded stream managers)
> fix(engine): Split generic Stream Manager from Redis specifics

- .vscode/launch.json
- apps/benchmark/simple-benchmark/api/create_api_file.sh
- apps/benchmark/simple-benchmark/config/app-config-docker.json
- apps/benchmark/simple-benchmark/config/app-config.json
- apps/benchmark/simple-benchmark/docker/bench-engine/config/supervisord.conf
- apps/benchmark/simple-benchmark/test/benchmark-docker.sh
- apps/benchmark/simple-benchmark/test/start-local.sh
- apps/benchmark/simple-benchmark/test/warm-up-fs.sh
- apps/examples/simple-example/api/create-openapi-file.sh
- apps/examples/simple-example/api/openapi.json
- apps/examples/simple-example/config/app-config.json
- apps/examples/simple-example/test/integration/conftest.py
- apps/examples/simple-example/test/integration/test_it_collect_spawn.py
- apps/examples/simple-example/test/integration/test_it_download_something.py
- apps/examples/simple-example/test/integration/test_it_list_somethings.py
- apps/examples/simple-example/test/integration/test_it_query_concurrently.py
- apps/examples/simple-example/test/integration/test_it_query_something.py
- apps/examples/simple-example/test/integration/test_it_query_something_extended.py
- apps/examples/simple-example/test/integration/test_it_upload_something.py
- docker/engine/config/supervisord.conf
- docs/source/benchmark/dedicated.rst
- docs/source/quickstart/dev.rst
- engine/src/hopeit/server/version.py
- engine/test/unit/app/test_app_config.py
- plugins/auth/basic-auth/config/plugin-config.json
- plugins/auth/basic-auth/test/unit/__init__.py
CHANGES:
=========
Configuration changes: matching example apps and plugins version to the engine version.
Matching is done using an env variable HOPEIT_ENGINE_VERSION that is created in version.py
Then plugins and app config json files embedded in the engine repo, use this variable to determine its version.
This way, each release of hopeit.engine will contain also a matching/tested release for plugins and apps.
Renamed config files to app-config.json and plugin-config.json accordingly.
> fix(apps/plugins): Match app/plugins version with engine release

- docs/source/release-notes.rst
- engine/requirements.txt
- engine/setup.py
- engine/src/hopeit/app/context.py
- engine/src/hopeit/cli/openapi.py
- engine/src/hopeit/cli/server.py
- engine/src/hopeit/server/version.py
- engine/src/hopeit/server/web.py
Fixes #62 
MOTIVATION:
==========
Since the introduction of PreprocessHook for multipart reading HTTP requests,
import EventContext withouth installing web dependencies was impossible.
SOLUTION:
=========
This PR removes dependency from context.py module to aiohttp by creating a Protocol for MultipartReader
and BodyPartReader. So EventContext, PreprocessHook can be imported i.e. from Jupyter notebooks or 
applications without the need of aiohttp when web server is not needed.
> fix(setup): Fix/aiohttp dependency

- engine/src/hopeit/server/steps.py
- engine/test/unit/server/test_steps.py
BUG: 
====
when splitting events with SHUFFLE step an intermediate stream is generated. This stream was missing the list of queus to read in case original event is not using default ["AUTO"] queue.
FIX:
===
Ensure generated intermediate streams contains queues equal to the original queues in read_stream of split event.
> fix(engine)): Fix queue propagation on steps stage splits (SHUFFLE step)

- docs/source/release-notes.rst
Fixed typos/redaction for release notes in 0.4.0.
> fix(docs): Fix release notes 0.4.0

- apps/examples/simple-example/src/simple_example/download_something.py
- apps/examples/simple-example/test/integration/test_it_download_something.py
- apps/examples/simple-example/test/integration/test_it_download_something_not_found.py
- docs/source/release-notes.rst
- engine/src/hopeit/app/api.py
- engine/src/hopeit/server/api.py
- engine/src/hopeit/server/version.py
- engine/test/mock_app/__init__.py
- engine/test/mock_app/mock_app_api_get_list.py
- engine/test/mock_app/mock_app_api_query_args.py
**FIX:  `date` and `datetime` types handling in query string parameters** :
Types support added:
- `date`
- `datetime`
When you create an openapi definition and set a query param as `datetime` type:
```
__api__ = event_api(
query_args=[('query_at', Optional[datetime], 'Overwrite query date')],
responses={
200: (Job, "Job Info")
}
)
```
API spec BEFORE:
```
..
"parameters": [
{
"name": "query_at'",
"in": "query",
"required": false,
"description": "Overwrite query date",
"schema": {
"type": "string"
}
},..
```
API spec NOW:
```
"parameters": [
{
"name": "query_at'",
"in": "query",
"required": false,
"description": "Overwrite query date",
"schema": {
"type": "string",
"format": "date-time"
}
},
```
**NOTE:**
When using a definition of `date` or `datetime` in query string parameters of the …
> fix(openapi): date and datetime types handled in query string parameters

- apps/examples/simple-example/setup.py
- plugins/auth/basic-auth/setup.py
Matching simple-example version to engine version.
NOTE:
=====
This change does not need a release, since simple-example is not released in PyPi,
this only affects mostly developers running simple-example locally.
> fix(apps) Fixed simple-example version to match engine

- apps/examples/simple-example/api/openapi.json
- docs/source/release-notes.rst
- engine/src/hopeit/server/logger.py
- engine/src/hopeit/server/version.py
- engine/test/integration/test_it_logger.py
- plugins/ops/config-manager/src/hopeit/config_manager/__init__.py
- plugins/ops/config-manager/src/hopeit/config_manager/client.py
- plugins/ops/config-manager/src/hopeit/config_manager/cluster_apps_config.py
- plugins/ops/config-manager/src/hopeit/config_manager/runtime_apps_config.py
- plugins/ops/config-manager/test/integration/__init__.py
- plugins/ops/config-manager/test/integration/conftest.py
- plugins/ops/config-manager/test/integration/test_client.py
- plugins/ops/config-manager/test/integration/test_cluster_apps_config.py
Added config-manager client that can be used later from apps-visualizer to retrieve configuration from multiple hosts.
This PR only setups the client in config-manager plugin,
it is not used yet from apps-visualizer.
Follow same steps as in #89 
now, when an unknown or irresponsive host is called, it will be reported in the response.
> plugin(config-manager): Added config manager client

- .vscode/launch.json
- apps/examples/simple-example/api/openapi.json
- docs/source/release-notes.rst
- engine/src/hopeit/app/api.py
- engine/src/hopeit/server/logger.py
- engine/src/hopeit/server/version.py
- engine/src/hopeit/server/web.py
- engine/src/hopeit/toolkit/auth.py
- plugins/auth/basic-auth/src/hopeit/basic_auth/__init__.py
- plugins/ops/apps-visualizer/api/openapi.json
Normalized $ signs in event names to / to prevent `404: Not found` when calling some management routes to start/stop stream events or services.
Fixes #97
> fix(engine): Fixed management route names

- .github/workflows/hopeit-engine-pypi-publishing.yml
- Makefile
- docs/source/release-notes.rst
- engine/src/hopeit/server/version.py
- Removed check-plugin test-plugin calls when making dist plugins
- Make a single QA call before releasing to PyPi
> fix(ci) Run single make qa before publishing to PyPi

- docs/source/release-notes.rst
- engine/src/hopeit/app/events.py
- engine/src/hopeit/server/steps.py
- engine/src/hopeit/server/version.py
- plugins/clients/apps-client/src/hopeit/apps_client/__init__.py
When events are split with SHUFFLE,
the second part of the event does not gain access to connections in settings,
so client calls fail.
This PR fixes this issue by sharing the same connections settings among pieces of split events.
> fix(apps-client): Fix issue with getting client connections for events split with SHUFFLE

- apps/examples/client-example/api/openapi.json
- apps/examples/simple-example/api/openapi.json
- docs/source/release-notes.rst
- engine/requirements-dev.txt
- engine/src/hopeit/cli/server.py
- engine/src/hopeit/server/engine.py
- engine/src/hopeit/server/version.py
- engine/src/hopeit/server/web.py
- engine/test/integration/server/test_it_web.py
- engine/test/unit/server/test_web.py
- plugins/ops/apps-visualizer/api/openapi.json
Fixes #122 
Reopens #123 and #124
> fix(engine): Streams startup on hopeit server start

- apps/examples/client-example/api/openapi.json
- apps/examples/simple-example/api/openapi.json
- docs/source/release-notes.rst
- engine/src/hopeit/server/api.py
- engine/src/hopeit/server/version.py
- engine/test/mock_app/__init__.py
- plugins/ops/apps-visualizer/api/openapi.json
- plugins/ops/apps-visualizer/src/hopeit/apps_visualizer/site/events_graph_template.html
Context:
-Apps visualizaer was failing for 2 reasons
1) Unable to connect to config-manager endpoints markes as "Unsecured" due a a global requirement for Bearer auth
2) Latest cytoscape version (>3.9) failing to match nodes to select proper format.
This pr fixes:
___________
Engine:
Plugin: apps-visualizer
> fix(engine / apps-visualizer) Fix auth by event & apps visualizer

- apps/examples/client-example/api/openapi.json
- apps/examples/simple-example/api/openapi.json
- docs/source/release-notes.rst
- engine/config/schemas/app-config-schema-draftv6.json
- engine/config/schemas/server-config-schema-draftv6.json
- engine/src/hopeit/cli/server.py
- engine/src/hopeit/server/version.py
- plugins/ops/apps-visualizer/api/openapi.json
Issue: 
------
Calling the `hopeit_server` command line without `--enabled-groups` parameter or with an empty one prevents start the server. 
Fix:
----
Set `--enabled-groups` as an optional parameter.
> bug(cli): `hopeit_server` command line without `--enabled-groups` parameter or with an empty one prevents start the hopeit.engine 

- apps/examples/client-example/api/openapi.json
- apps/examples/simple-example/api/openapi.json
- docs/source/release-notes.rst
- engine/src/hopeit/server/version.py
- plugins/ops/apps-visualizer/api/openapi.json
- plugins/storage/fs/setup.py
Version 0.16.5
______________
Plugin: 
- fs-storage: include `hopeit.fs_storage.events` module in release package
> plugin(fs-storage): Added missing `events` package

- apps/examples/client-example/api/openapi.json
- apps/examples/simple-example/api/openapi.json
- docs/source/release-notes.rst
- engine/src/hopeit/app/config.py
- engine/src/hopeit/server/version.py
- plugins/ops/apps-visualizer/api/openapi.json
- plugins/ops/apps-visualizer/config/plugin-config.json
- plugins/ops/config-manager/config/plugin-config.json
- plugins/ops/config-manager/src/hopeit/config_manager/client.py
- plugins/ops/config-manager/test/integration/__init__.py
- plugins/ops/config-manager/test/integration/test_client.py
- plugins/ops/config-manager/test/integration/test_cluster_apps_config.py
When the app-visualizer queries a locking server it waits indefinitely for a response. This leads to unresponsive front-end
Timeout need to be added here: https://github.com/hopeit-git/hopeit.engine/blob/master/plugins/ops/config-manager/src/hopeit/config_manager/client.py
closes #116
> fix(apps-visualizer): missing client timeout on request to config-manager

- apps/examples/client-example/api/openapi.json
- apps/examples/simple-example/api/openapi.json
- docs/source/release-notes.rst
- engine/src/hopeit/server/version.py
- plugins/ops/apps-visualizer/api/openapi.json
- plugins/storage/fs/src/hopeit/fs_storage/__init__.py
Large File Name RENAME ERROR (Win Error 3) 
Using shutil.move instead of os.rename that does not work properly with long file names in windows.
> fix(fs-storage): Large File Name RENAME ERROR (Win Error 3)

- .vscode/launch.json
- Makefile
- apps/examples/client-example/api/openapi.json
- apps/examples/dataframes-example/api/openapi.json
- apps/examples/simple-example/api/openapi.json
- docker/docker-compose.yml
- docs/source/release-notes.rst
- engine/config/schemas/app-config-schema-draftv6.json
- engine/config/schemas/server-config-schema-draftv6.json
- engine/src/hopeit/app/api.py
- engine/src/hopeit/server/version.py
- plugins/data/dataframes/src/hopeit/dataframes/dataframe.py
- plugins/data/dataframes/src/hopeit/dataframes/serialization/dataset.py
- plugins/data/dataframes/src/hopeit/dataframes/serialization/files.py
- plugins/data/dataframes/test/integration/conftest.py
- plugins/data/dataframes/test/integration/test_dataframe.py
- plugins/data/dataframes/test/integration/test_dataframes_api.py
- plugins/ops/apps-visualizer/api/openapi.json
> plugin(dataframes): Dataframes schema evolution support

- apps/examples/client-example/api/openapi.json
- apps/examples/dataframes-example/api/openapi.json
- apps/examples/simple-example/api/openapi.json
- docs/source/release-notes.rst
- engine/config/schemas/app-config-schema-draftv6.json
- engine/config/schemas/server-config-schema-draftv6.json
- engine/src/hopeit/server/version.py
- engine/test/unit/server/test_server.py
- engine/test/unit/server/test_web.py
- plugins/data/dataframes/src/hopeit/dataframes/__init__.py
- plugins/data/dataframes/src/hopeit/dataframes/dataframe.py
- plugins/data/dataframes/test/integration/conftest.py
- plugins/data/dataframes/test/integration/test_dataframe.py
- plugins/data/dataframes/test/integration/test_dataframes_api.py
- plugins/ops/apps-visualizer/api/openapi.json
Version 0.25.2
______________
- Plugins:
- DataFrames:
- Support for `bool` fields
- `Dataframes.to_dataobjects`: option to convert null values (`nan`, `NaT`, etc) to None
> fix(dataframes): dataframes datetime type mapping & boolean support

- apps/examples/client-example/api/openapi.json
- apps/examples/dataframes-example/api/openapi.json
- apps/examples/simple-example/api/openapi.json
- docs/source/release-notes.rst
- engine/config/schemas/app-config-schema-draftv6.json
- engine/config/schemas/server-config-schema-draftv6.json
- engine/src/hopeit/app/config.py
- engine/src/hopeit/server/version.py
- engine/src/hopeit/server/web.py
- plugins/ops/apps-visualizer/api/openapi.json
Version 0.25.3
______________
- Engine:
- Web:
- Allow to specify `cors_routes_prefix` to allow `cors_origin` to be applied
to custom routes names
> Allow to specify cors_routes_prefix to allow cors_origin to be applied  to custom route names

- apps/examples/simple-example/api/openapi.json
- apps/examples/simple-example/config/app-config.json
- apps/examples/simple-example/src/simple_example/check_enum.py
- engine/requirements.txt
- engine/setup.py
- plugins/ops/apps-visualizer/test/integration/effective_events.json
- plugins/ops/apps-visualizer/test/integration/events_graph_data_expanded.json
- plugins/ops/apps-visualizer/test/integration/events_graph_data_standard.json
- plugins/ops/config-manager/test/integration/runtime_simple_example.json
> chore(deps): unpinned aiohttp 3 after aiohttp-swagger 0.10 release
